apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-blue
  labels:
    app: frontend
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      color: blue
  template:
    metadata:
      labels:
        app: frontend
        color: blue
    spec:
      containers:
        - name: frontend
          image: appacr1603.azurecr.io/frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"